Classification evaluation
Blubberli/ambiguous-alpaca pull request #61
Opened 2020-04-01 12:35 UTC by evahuber1994

This PR contains an addition to the evaluation script.
- Two methods were included to write per class f1 to a file, and if the (new) flag --confusion_matrix is true then it also writes a confusion_matrix to a csv file.
- the paths were changed to "model_path" +"save_name"

2020-04-02 12:05 UTC, Blubberli requested changes
I have some comments. There is also a bug in the ranking method which I fixed and a method to plot the confusion matrix. I will commit these two changes to this branch.

2020-04-02 12:05 UTC, Blubberli commented on scripts/evaluation.py
> +def class_performance_classification(path_results, gold_loader, dataloader, eval_path):
dataloader is a missleading parameter name. it is not da dataloader but a dataset.

2020-04-02 12:05 UTC, Blubberli commented on scripts/evaluation.py
> +    report = classification_report(gold, preds, output_dict=True)
I think for readability it would be better to not report numbers with like 12 decimals, but I would set it to 3. (parameter digits: 3)

2020-04-02 12:05 UTC, Blubberli commented on scripts/evaluation.py
> +    gold = gold["l"].numpy()
if we store these values also in a set we can give it as a parameter to 'classification_report' (target_names). The report will then only include the results for the labels that actually occur in the test data. at the moment I basically have to scroll through the report to find my labels of interest

2020-04-02 12:05 UTC, Blubberli commented on scripts/evaluation.py
method documentation is missing

2020-04-02 12:05 UTC, Blubberli commented on scripts/evaluation.py
> +                confusion_matrix(prediction_path_dev, valid_loader, dataset_valid, conf_path_dev)
your are trying to call the sklearn method "confusion_matrix". I suppose this is not intended. did you want to call your method "confusion_matrix_classification"?

2020-04-02 12:05 UTC, Blubberli commented on scripts/evaluation.py
> +def confusion_matrix_classification(path_results, gold_loader, dataloader, conf_path):
again, rename parameter "dataloader"

2020-04-02 12:05 UTC, Blubberli commented on scripts/evaluation.py
> +                confusion_matrix_classification(prediction_path_test, test_loader, dataset_test, conf_path_test)
with more than three arguments, named parameter are more convenient for people who have not written the code.

2020-04-07 07:15 UTC, evahuber1994 commented on scripts/evaluation.py
> +    gold = gold["l"].numpy()
you mean that we can give it to the confusion matrix? The classification report only inlcudes the labels occurring in the test data.

2020-04-07 07:16 UTC, evahuber1994 commented on scripts/evaluation.py
> +                confusion_matrix(prediction_path_dev, valid_loader, dataset_valid, conf_path_dev)
seems like I forgot to commit that, I obviously changed that :-)

2020-04-07 12:11 UTC, Blubberli approved these changes
Thanks for the changes. Looks good to me!

2020-04-07 12:11 UTC, merged