joint training of composition model
Blubberli/ambiguous-alpaca pull request #74
Opened 2020-04-29 10:01 UTC by Blubberli

This PR contains the functionality to jointly train a composition model on two tasks. The model takes as input two words and constructs three representations. for example:
word1: hot
word2: weather

the vectors for "hot" and "temperature" are transformed by a number of matrices and result in the same number of transformed vectors
representation 1: separate weighting combines the transformed vectors into representation 1: this representation is trained to be close to the original phrase (gold(hot_ weather)) 
representation 2: separate weighting combines the transformed vectors into representation 2: this representation is trained to be close to the implicit relation /attribute that holds between hot in weather which is temperature
composed: representation 1 and 2 are combined into a final representation by weighting each and adding them (and then normalizing them). Thus, this representation should capture the general meaning of the phrase but also the implicit attribute

we compute two losses:
loss 1: cosine distance(representation 1 , original phrase representation)
loss 2: cosine distance(representation 2, attribute)
we back propagate based on the combined loss (loss 1 + loss 2). 
--> those could be weighted but when I ran the model the losses for both tasks were more or less balanced (the one for phrase reconstruction was a bit lower)

I added one epoch of pretraining because the reconstruction task theoretically has a lot more different labels to lean and thus,  is more complicated. This could be optional or even left out if there is not a big difference but I would do that in a second PR

I currently evaluate the model on attribute ranking based on the nearest neighbor ranker. I report the result for representation 2 (attribute specific representation) as well as for the final representation. It might make sense to add representation 1 as well later on.

To train the model I needed to add a new dataset type but it is very simple. it takes two datasets and returns a batch for each, so that when you iterate in training you get two batches at the same time, one contains phrases with attributes and one phrases with phrase representations. I compute loss one for the phrase batch and loss 2 for the attribute batch and use these losses to backpropagate

a test is added as well.

the PR is very long, especially the training script, so take your time to review it. 

- we probably want to add a simpler model (matrix) model as a joint model as well. but we can do that in a second PR....

2020-05-01 10:33 UTC, evvahu requested changes
I only request one change in evaluate (training scripts), the other comments are questions for my personal understanding. 

I have some other questions/remarks that I'd like to ask here:
- for this model we will have to tune: dropout, nr of transformations and weights for combining the two representations right? 
- it'd be nice if we had a simpler, for example, matrix model to compare it to. I'd like to take on this task if that's okay? I would like to programme something again so that I can practice more.
-it would also be nice if we can parameterise the pretraining as you mentioned. that shouldn't be difficult.
-as you said we should possibly also evaluate on the representation of the phrase. In the end we should probably use both representations (the composed one and the phrase only one) to do WSD? I'm not sure whether you've already tried it out (I think not?)

and now a really stupid question I should have asked ages ago because it also applies to the ranking models in general. It might have been clear to me at some point but at the moment "stehe ich völlig auf dem Schlauch".
So in the case of the present model, you calculate cosine_distance_loss based on the predicted representation (e.g. for 'hot weather' and the attribute which looks hopefully somewhat like 'temperature') and the gold representation (both the phrase and the attribute). Where do we get the gold representations from?  

I have been a bit absent in terms of the programming tasks in this project and forgotten some stuff already so I'd like to engage more if time allows.

2020-05-01 10:33 UTC, evvahu commented on training_scripts/joint_training.py
> +    ranker_attribute = NearestNeigbourRanker(path_to_predictions=predictions_att_rep,
needs to be changed according to changes in NearestNeighbourRanker

2020-05-01 10:33 UTC, evvahu commented on training_scripts/joint_training.py
> +        batch["device"] = device
I don't really understand these lines (batch["device"] = device). why do you save device in the config dict?

2020-05-01 10:33 UTC, evvahu commented on training_scripts/joint_training.py
> +        batch["device"] = device
okay, I see it's because "model" takes the batch object as its argument.

2020-05-01 10:33 UTC, evvahu commented on training_scripts/joint_training.py
> +            predictions_final_rep.append(pred.detach().numpy())
do I get this right that you have to call .detach because you can't call numpy() on a variable that requires grad?

2020-05-04 06:47 UTC, Blubberli commented on training_scripts/joint_training.py
> +        batch["device"] = device
it doesn't make a difference when you train on cpu but on gpu, you need to explicitly set the device to gpu at the positions were you want the operations to be performed.

2020-05-04 06:49 UTC, Blubberli commented on training_scripts/joint_training.py
> +            predictions_final_rep.append(pred.detach().numpy())
yes, we only want the array and not the variable. but I think there are other options to that. e.g we can call pred.data to only get the array and np.array(pred.data) to do the same thing in general (I think, haven't tested that code).

2020-05-04 07:04 UTC, Blubberli commented
> I only request one change in evaluate (training scripts), the other comments are questions for my personal understanding.
> 
> I have some other questions/remarks that I'd like to ask here:
> 
> * for this model we will have to tune: dropout, nr of transformations and weights for combining the two representations right?
> * it'd be nice if we had a simpler, for example, matrix model to compare it to. I'd like to take on this task if that's okay? I would like to programme something again so that I can practice more.
>   -it would also be nice if we can parameterise the pretraining as you mentioned. that shouldn't be difficult.
>   -as you said we should possibly also evaluate on the representation of the phrase. In the end we should probably use both representations (the composed one and the phrase only one) to do WSD? I'm not sure whether you've already tried it out (I think not?)
> 
> and now a really stupid question I should have asked ages ago because it also applies to the ranking models in general. It might have been clear to me at some point but at the moment "stehe ich völlig auf dem Schlauch".
> So in the case of the present model, you calculate cosine_distance_loss based on the predicted representation (e.g. for 'hot weather' and the attribute which looks hopefully somewhat like 'temperature') and the gold representation (both the phrase and the attribute). Where do we get the gold representations from?
> 
> I have been a bit absent in terms of the programming tasks in this project and forgotten some stuff already so I'd like to engage more if time allows.

Thanks for the extensive feedback and remarks. 
1) Yes you are right with the parameters
2) simpler model would be nice. matrix model sounds good, though we are facing one problem: the matrix model only has one parameter block (one matrix). thus, if we jointly train this model there are no task specific parameters. one possibility would be to try it without task specific parameters, but then you could also just smash the two datasets into one, increase the number of labels and that's it. another option would be to keep one matrix as a joint parameter but add one task-specific matrix on top of the composed representation for each task. so after retrieving the general composed representation (that should capture the similarities between both tasks) we can transform it with a 200x200 matrix for an attribute representation and with a different 200x200 matrix for the phrase representation. this model would still be simpler and smaller than the transformation model but would make sense in terms of multitask learning. what do you think? I'd be happy if you could program something like that.
3) we should evaluate the distinct representations on WSD. We can even evaluate all three representations (phrase, attribute, combined)
4) the gold representation for the attribute is taken from the same embedding space as all other Word Embeddings (in this case temperature). of course by doing that we make a strong assumption, namely that attributes have a meaningful representation in this vector space. that's why I always need to rephrase attributes like Art&Weise because I cannot get an embedding for that. previous work on attribute learning used other types of representations (i.e. a specific attribute vector space, and then you really have each dimension corresponding to a specific word in context. Hartung has done that before word embedding became a thing and then in the 2017 paper compared these to Word Embeddings (he used w2vec and also did not have a representation for each of his attributes) and you can see that the "traditional" representations are not very powerful unfortunately. But nevertheless, I don't think that every attribute is perfectly represented by a pretrained word embedding and other representations might be worth a try (though I don't see time to do that at the moment)

ok, hoffe ich hab jetzt nix vergessen^^

2020-05-04 07:05 UTC, Blubberli commented on training_scripts/joint_training.py
> +    ranker_attribute = NearestNeigbourRanker(path_to_predictions=predictions_att_rep,
how do I need to change that?

2020-05-04 12:58 UTC, Blubberli commented on training_scripts/joint_training.py
> +    ranker_attribute = NearestNeigbourRanker(path_to_predictions=predictions_att_rep,
done

2020-05-05 10:18 UTC, merged